name: "Terraform"

on:
  push:
    branches:
      - 'TerraformDev'
      - 'TerraformStage'
      - 'main'



jobs:
  ecs_deployment_dev:
    if: github.ref == 'refs/heads/TerraformDev'
    name: "ECS Fargate Dev Deployment"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/TerraformDev'

      - id: tool-versions
        name: Set tool versions
        run: |
          printf '::set-output name=terraform::%s\n' "$(<.terraform-version)"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: "${{ steps.tool-versions.outputs.terraform }}"
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.DEV_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        id: init
        run: |
          cd service-users
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd service-users
          terraform validate -no-color

      - name: Terraform Workspace
        id: workspace-dev
        run: |
          cd service-users
          terraform workspace select dev

      - name: Terraform Plan and Apply
        id: terraform-plan-apply
        run: |
          cd service-users
          terraform plan -var-file terraform_dev.tfvars -out terraform.out
          terraform apply "terraform.out"

          
          
      